### PR TITLE
Added method for uploading files

### PR DESCRIPTION
**Pull request by Da9elKH**
- Added `Teamtailor#upload` and `client#create_uploads`
- Added rspec for parsing uploads

### CODE REVIEW

**Comment by bzf** [comment]
@Da9elKH Could you rebase this against `main` and remove the commits that are already merged and I'll have a look afterwards 😊 👍🏽

**Comment by Da9elKH** [comment]
> @Da9elKH Could you rebase this against `main` and remove the commits that are already merged and I'll have a look afterwards 😊 👍🏽

I will look into that next week! I have not removed commits before, but I guess I will figure it out! 😅

**Comment by bzf** [comment]
@Da9elKH They should disappear when you rebase by themselves. 😄 

If you want some help on that topic, Upcase has a video series about using `git` that really helped me understand some of the more complicated parts of it. There's an episode focused on rebasing which could be interesting for you, so I'll leave it here if you want to check it out 😊 

https://thoughtbot.com/upcase/videos/git-crafting-history

**Comment by Da9elKH** [comment]
@bzf What is the status of this pull request? :)

**Comment by bzf** [comment]
@Da9elKH Sorry, I was planning to look at it last week. 🙈 

Everything looks good to me, great work! 🎉 

I'll merge it in and will do a release during the day, thanks for the contribution 😄

**Comment by bzf** [comment]
Released in 0.4.0

**Pull request merged**
